name: object-detection-thesis-cpu-env

dependencies:
  - python==3.7
  - pip
  - matplotlib
  - opencv
  - pip:
    - tensorflow==2.0.1
    - lxml
    - tqdm
    - flask
    - seaborn
    - pillow
    - setuptools
    - cython
    - matplotlib
    - opencv-python
    - pyococotools
    - scikit-image
    - keras
    - h5py
    - imgaug
    - IPython[all]
